openapi: 3.0.0
info:
  title: thoughtTrackingJournal API
  description: A REST API for organizing and tracking thoughts to gain more
    clarity in thoughts related to worries and anxieties and possibly finding solutions
  version: 1.0.0
servers:
  - url: http://localhost:3000 # local server

paths:
  /users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: 'exampleUser'
                Password:
                  type: string
                  example: 'password123'
                Email:
                  type: string
                  example: 'exampleUser@example.com'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Sever Error

  /users/{userId}:
    put:
      summary: Update user information
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: 'newUserName'
                Password:
                  type: string
                  example: 'newPassword123'
                Email:
                  type: string
                  example: 'newEmail@example.com'
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found
    delete:
      summary: User can deregister
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User successfully deleted
        '404':
          description: User not found
        '500':
          description: Internal server error

  /thoughts:
    post:
      summary: Add a new thought (Name a specific thought)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thoughtName:
                  type: string
                  example: 'Thought1'
                Description:
                  type: string
                  example: 'Details about the thought'
                Emotions:
                  type: array
                  items:
                    type: string
                    example: 'anxiety'
                Problems:
                  type: array
                  items:
                    type: string
                    example: 'this is an example problem'
                possibleSolutions:
                  type: array
                  items:
                    type: string
                    example: 'This is an example solution.'
                Affirmation:
                  type: string
                  example: 'I got this.'
                user:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Thought created successfully
        '500':
          description: Internal server error
    get:
      summary: Get a list of all user thoughts
      responses:
        '200':
          description: Successful retrieval of thoughts
        '500':
          description: internal server error

  /thoughts/{thoughtId}:
    put:
      summary: Update a specific thought
      parameters:
        - in: path
          name: thoughtId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thoughtName:
                  type: string
                  example: 'Updated Thought'
                Description:
                  type: string
                  example: 'Updated details about the thought'
                Emotions:
                  type: array
                  items:
                    type: string
                    example: 'happiness'
                Problems:
                  type: array
                  items:
                    type: string
                    example: 'Adding or updating problems'
                possibleSolutions:
                  type: array
                  items:
                    type: string
                    example: 'plan ahead'
                Affirmation:
                  type: string
                  example: 'I am strong and capable.'
                user:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Successfully updated thought
        '404':
          description: Thought not found
    delete:
      summary: Delete a thought
      parameters:
        - in: path
          name: thoughtId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Thought successfully deleted
        '404':
          description: Thought not found
        '500':
          description: Internal server error
